version: '3.9'
services:
  kotlin-wasm-app:
    networks:
      - frontend
    container_name: test-app
    hostname: test-app
    restart: always
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./:/codex

networks:
  frontend:
    name: custom_network
    driver: bridge